jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - script: conda create --yes --quiet --name arcs_CI
    displayName: Create Anaconda environment
  - script: |
      source activate arcs_CI
      conda install --yes -c conda-forge -c bioconda compilers btllib boost automake sparsehash clang-format=18 clang-tools python pylint
    displayName: Install dependencies
  - script: |
      source activate arcs_CI
      make -C Arcs clang-format
      make -C src lint
    displayName: Run clang-format
  - script: |
      source activate arcs_CI
      ./autogen.sh
      ./configure CXXFLAGS="${CXXFLAGS} -Wno-error=dangling-reference"
      make
      ./Arcs/arcs --version
    displayName: Compile ARCS
  - script: |
      source activate arcs_CI
      cd Examples
      pylint makeTSVfile.py
      cd ../
    displayName: Run pylint
  - script: |
      source activate arcs_CI
      make distcheck
    displayName: Compile ARCS with make distcheck
  - script: |
      source activate arcs_CI
      make -C src all
    displayName: Compile long-to-linked-pe

- job:
  displayName: mac-latest
  pool:
    vmImage: 'macOS-latest'

  steps:
  - script: |
      mkdir -p ~/miniforge3
      curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-x86_64.sh  -o ~/miniforge3/miniforge.sh
      bash ~/miniforge3/miniforge.sh -b -u -p ~/miniforge3
      rm -rf  ~/miniforge3/miniforge.sh
      ~/miniforge3/bin/conda init bash
      ~/miniforge3/bin/conda init zsh
      export CONDA=$(realpath ~/miniforge3/bin)
      echo "##vso[task.prependpath]$CONDA"
    displayName: Install conda
  - script: conda create --yes --quiet --name arcs_CI
    displayName: Create Anaconda environment
  - script: |
      source activate arcs_CI
      mamba install --yes -c conda-forge -c bioconda compilers btllib boost automake sparsehash
    displayName: Install dependencies
  - script: |
      source activate arcs_CI
      ./autogen.sh
      ./configure
      make
    displayName: Compile ARCS
