#!/bin/bash

# MacOS does not necessarily have coreutils installed, but Python should be as btllib requires it
function portable_realpath() {
  python3 -c 'import os, sys; print(os.path.realpath(sys.argv[1]))' $1
}
