#!/bin/bash

if [ -z "${MESON_SOURCE_ROOT}" ]; then
  echo "[ERROR] This script can only be ran with meson!"
  exit 1
fi

set -e

cd "${MESON_SOURCE_ROOT}"

# Check if clang is present
set +e
command -v clang >/dev/null
if [[ $? -eq 1 ]]; then
  echo "[ERROR] Clang compiler must be used for memory sanitization, but it is missing!"
  exit 1
fi
set -e

# GCC does not seem to support memory sanitization
export CXX=clang
export CC=clang

builddir="${MESON_BUILD_ROOT}/__build-sanitize-memory"
meson setup -Db_sanitize=memory ${builddir} -Db_lundef=false
cd ${builddir}
ninja test
rm -rf ${builddir}