#!/bin/bash

if [ -z "${MESON_SOURCE_ROOT}" ]; then
  echo "[ERROR] This script can only be ran with meson!"
  exit 1
fi

set -e

cd "${MESON_SOURCE_ROOT}"

# Check if clang is present
set +e
command -v clang >/dev/null
if [[ $? -eq 1 ]]; then
  echo "[ERROR] Clang compiler must be used for thread sanitization, but it is missing!"
  exit 1
fi
set -e

# GCC gives false positives when sanitizing threads if OpenMP is used
# Clang on the other hand seems to handle this properly
export CXX=clang
export CC=clang
export TSAN_OPTIONS='ignore_noninstrumented_modules=1'

builddir="${MESON_BUILD_ROOT}/__build-sanitize-thread"
meson setup -Db_sanitize=thread ${builddir} -Db_lundef=false
cd ${builddir}
ninja test
rm -rf ${builddir}