#!/bin/bash

if [ -z "${MESON_SOURCE_ROOT}" ]; then
  echo "[ERROR] This script can only be ran with meson!"
  exit 1
fi

set -e

cd "${MESON_SOURCE_ROOT}"

builddir="${MESON_BUILD_ROOT}/__build-sanitize-address"
meson setup -Db_sanitize=address ${builddir}
cd ${builddir}
ninja test
rm -rf ${builddir}